[package]
name = "aoc22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"


[[bin]]
name = "01"
path = "src/01rs/01.rs"

[[bin]]
name = "02"
path = "src/02rs/02.rs"
